// Maintainer task only. Readers and normal builds never contact Google.
import { readFile, writeFile, mkdir, access } from "node:fs/promises";
import { createHash } from "node:crypto";

const catalogue = JSON.parse(
  await readFile(
    new URL("../src/lib/google-fonts.json", import.meta.url),
    "utf8",
  ),
);
const root = new URL("../public/fonts/", import.meta.url);
await mkdir(root, { recursive: true });
const headers = {
  "User-Agent":
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
};
async function fetchOk(url) {
  const response = await fetch(url, {
    headers,
    signal: AbortSignal.timeout(60000),
  });
  if (!response.ok) throw new Error(`${response.status}: ${url}`);
  return response;
}
const metadata = JSON.parse(
  (
    await (await fetchOk("https://fonts.google.com/metadata/fonts")).text()
  ).replace(/^\)\]\}'\n/, ""),
);
const sources = [];
async function syncFont(font) {
  const meta = metadata.familyMetadataList.find(
    (item) => item.family === font.name,
  );
  if (!meta?.isOpenSource)
    throw new Error(`Missing open-source family: ${font.name}`);
  const weightAxis = meta.axes.find((axis) => axis.tag === "wght");
  const italic = Object.keys(meta.fonts).some((style) => style.endsWith("i"));
  const styles = italic ? [0, 1] : [0];
  const values = styles.flatMap((style) => {
    const weights = weightAxis
      ? [`${Math.max(400, weightAxis.min)}..${Math.min(700, weightAxis.max)}`]
      : Object.keys(meta.fonts)
          .filter((weight) => weight.endsWith("i") === Boolean(style))
          .map(Number.parseFloat)
          .filter((weight) => [400, 600, 700].includes(weight))
          .map(String);
    if (!weights.length) throw new Error(`No reading weights: ${font.name}`);
    return weights.map((weight) => (italic ? `${style},${weight}` : weight));
  });
  const api = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(font.name)}:${italic ? "ital,wght" : "wght"}@${values.join(";")}&display=swap`;
  let css = await (await fetchOk(api)).text();
  const urls = [
    ...new Set(
      [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map(
        (match) => match[1],
      ),
    ),
  ];
  if (!urls.length) throw new Error(`No font files: ${font.name}`);
  for (const url of urls) {
    const file = `${font.id}-${createHash("sha256").update(url).digest("hex").slice(0, 12)}.woff2`;
    const destination = new URL(file, root);
    try {
      await access(destination);
    } catch {
      const bytes = Buffer.from(await (await fetchOk(url)).arrayBuffer());
      if (bytes.toString("ascii", 0, 4) !== "wOF2")
        throw new Error(`Not WOFF2: ${url}`);
      await writeFile(destination, bytes);
    }
    css = css.replaceAll(url, `/fonts/${file}`);
  }
  // The distributed files retain their original family names and licences.
  const directory = font.name.toLowerCase().replace(/[^a-z0-9]/g, "");
  let license;
  for (const path of [
    `ofl/${directory}/OFL.txt`,
    `apache/${directory}/LICENSE.txt`,
    `ufl/${directory}/UFL.txt`,
  ]) {
    const url = `https://raw.githubusercontent.com/google/fonts/main/${path}`;
    const response = await fetch(url, { signal: AbortSignal.timeout(30000) });
    if (response.ok) {
      license = { url, text: await response.text() };
      break;
    }
    if (response.status !== 404)
      throw new Error(`Licence request failed: ${url}`);
  }
  if (!license) throw new Error(`Missing licence: ${font.name}`);
  await writeFile(new URL(`${font.id}-LICENSE.txt`, root), license.text);
  sources.push({ family: font.name, css: api, license: license.url });
  console.log(`Saved ${font.name} (${urls.length} subsets/styles)`);
  return css;
}

// Keep upstream traffic bounded; emit the stylesheet only after every family succeeds.
const sheets = new Array(catalogue.length);
let next = 0;
await Promise.all(
  Array.from({ length: 4 }, async () => {
    while (next < catalogue.length) {
      const index = next++;
      sheets[index] = await syncFont(catalogue[index]);
    }
  }),
);
const variables = catalogue
  .map((font) => `  --font-${font.id}: "${font.name}";`)
  .join("\n");
await writeFile(
  new URL("../src/app/font-faces.css", import.meta.url),
  `/* Generated by npm run fonts:sync. Font files load only when used. */\n:root {\n${variables}\n}\n\n${sheets.join("\n")}`,
);
await writeFile(
  new URL("SOURCES.json", root),
  JSON.stringify(
    sources.sort((a, b) => a.family.localeCompare(b.family)),
    null,
    2,
  ) + "\n",
);
console.log(`Self-hosted ${catalogue.length} Google Fonts, with licences.`);
